#!/bin/sh
# Get the current branch
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "f-droid" ]; then
    # Verify that the pubspec.yaml doesn't contain certain dependencies
fi
